"""empty message

Revision ID: 65edcc47e4ed
Revises: c9d6313461dd
Create Date: 2020-05-24 17:13:03.346660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65edcc47e4ed'
down_revision = 'c9d6313461dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
