"""empty message

Revision ID: 822f4b068d9c
Revises: 65edcc47e4ed
Create Date: 2020-05-24 18:02:21.924205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822f4b068d9c'
down_revision = '65edcc47e4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
